/* Brand values and logo assets follow SocraNextRebuild/client/src/styles/index.css.
   Fonts are bundled with their SIL Open Font Licenses; no external font request. */
@font-face{font-family:SocraNextMontserrat;font-style:normal;font-weight:400;font-display:swap;src:url("{{ asset('vendor/socranext/fonts/montserrat-400.ttf') }}") format('truetype')}
@font-face{font-family:SocraNextMontserrat;font-style:normal;font-weight:500;font-display:swap;src:url("{{ asset('vendor/socranext/fonts/montserrat-500.ttf') }}") format('truetype')}
@font-face{font-family:SocraNextMontserrat;font-style:normal;font-weight:600;font-display:swap;src:url("{{ asset('vendor/socranext/fonts/montserrat-600.ttf') }}") format('truetype')}
@font-face{font-family:SocraNextPoppins;font-style:normal;font-weight:500;font-display:swap;src:url("{{ asset('vendor/socranext/fonts/poppins-500.ttf') }}") format('truetype')}
@font-face{font-family:SocraNextPoppins;font-style:normal;font-weight:600;font-display:swap;src:url("{{ asset('vendor/socranext/fonts/poppins-600.ttf') }}") format('truetype')}
@font-face{font-family:SocraNextPoppins;font-style:normal;font-weight:700;font-display:swap;src:url("{{ asset('vendor/socranext/fonts/poppins-700.ttf') }}") format('truetype')}
.sncp{--sn-ink:#000040;--sn-muted:#64748b;--sn-border:#e5e7eb;--sn-card:#fff;--sn-soft:#f8fafc;--sn-accent:#6d28d9;--sn-good:#6d28d9;color:var(--sn-ink);max-width:1180px;margin:0 auto;padding:10px 4px 28px;font-family:SocraNextMontserrat,Inter,system-ui,sans-serif;font-size:14px;line-height:1.55}
.dark .sncp{--sn-ink:#f8fafc;--sn-muted:#b7c0d1;--sn-border:#374151;--sn-card:#20212b;--sn-soft:#2a2b39;--sn-accent:#c4b5fd;--sn-good:#c4b5fd}
.sncp h1,.sncp h2,.sncp h3,.sncp p{margin:0}.sncp h1,.sncp h2,.sncp h3{font-family:SocraNextPoppins,Inter,system-ui,sans-serif}
.sncp-header{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:26px}
.sncp-eyebrow{font-size:10px;font-weight:700;letter-spacing:.16em;color:var(--sn-muted);margin-bottom:7px!important}
.sncp h1{display:flex;align-items:center;gap:14px;font-size:29px;line-height:1.2;font-weight:600;letter-spacing:-.035em}
.sncp-preview{font-size:10px;letter-spacing:0;font-weight:500;line-height:1.3;border:1px solid var(--sn-border);border-radius:5px;padding:4px 7px;color:var(--sn-muted)}
.sncp-lead{margin-top:10px!important;max-width:620px;color:var(--sn-muted)}
.sncp-button{display:inline-flex;align-items:center;justify-content:center;gap:14px;min-height:39px;padding:9px 15px;border-radius:8px;border:1px solid transparent;line-height:1.3;font-size:13px;font-weight:600;cursor:pointer;text-decoration:none;white-space:normal;transition:background .15s,box-shadow .15s}
.sncp-button:focus-visible,.sncp summary:focus-visible,.sncp a:focus-visible,.sncp input:focus-visible{outline:3px solid #06b6d4;outline-offset:3px}
.sncp-button-primary{background:#6d28d9;color:#fff;box-shadow:0 1px 2px #00004026}.sncp-button-primary:hover{background:#581eb1}
.sncp-button-secondary{border-color:var(--sn-border);background:var(--sn-card);color:var(--sn-ink);box-shadow:0 1px 2px #00004010}.sncp-button-secondary:hover{background:var(--sn-soft)}
.sncp-button-danger{background:transparent;border-color:var(--sn-border);color:#b93c37}.dark .sncp-button-danger{color:#ffa7a1}.sncp-button-danger:hover{background:#fa777712}
.sncp-hero{display:flex;align-items:center;justify-content:space-between;gap:24px;overflow:hidden;border-radius:15px;background:radial-gradient(ellipse at 95% 15%,#06b6d430,transparent 55%),radial-gradient(ellipse at 75% 100%,#6d28d955,transparent 65%),#000040;color:#fff;padding:30px 34px;margin-bottom:20px}
.sncp-hero-copy{max-width:660px}.sncp-connection{display:inline-flex;flex-wrap:wrap;align-items:center;gap:8px;color:#dbeafe;font-size:12px;overflow-wrap:anywhere}
.sncp-dot{width:7px;height:7px;background:#cbd5e1;border-radius:50%}.sncp-dot.is-connected{background:#06b6d4;box-shadow:0 0 0 4px #06b6d414}
.sncp-hero h2{font-size:30px;line-height:1.22;letter-spacing:-.02em;font-weight:600;margin:14px 0 10px}.sncp-hero p{color:#dbeafe;max-width:520px}
.sncp-actions{display:flex;align-items:center;flex-wrap:wrap;gap:20px;margin-top:23px}.sncp-hero-link{color:#fff;font-size:13px;text-decoration:underline;text-underline-offset:4px}
.sncp-visual{display:flex;align-items:center;justify-content:center;flex-direction:column;gap:16px;flex-shrink:0;padding:20px 8px 20px 30px}.sncp-visual img{width:106px;height:106px;padding:15px;background:#fff;border-radius:24px;box-shadow:0 15px 35px #00004050}.sncp-visual>span{font-size:11px;color:#dbeafe}

.sncp-status-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px}.sncp-status{display:flex;align-items:flex-start;gap:12px;background:var(--sn-card);border:1px solid var(--sn-border);border-radius:11px;padding:19px 20px}.sncp-status h2{font-size:13px;font-weight:600;display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-bottom:5px}.sncp-status p{font-size:12px;color:var(--sn-muted)}
.sncp-status-icon{display:flex;align-items:center;justify-content:center;flex-shrink:0;width:30px;height:30px;border-radius:9px;background:var(--sn-soft);color:var(--sn-muted);font-size:14px}.sncp-pill{font-size:10px;font-weight:500;color:var(--sn-muted);background:var(--sn-soft);padding:2px 7px;border-radius:5px}.sncp .is-good{color:var(--sn-good)}.sncp-status-icon.is-good{background:#6d28d914}
.sncp-panel{border:1px solid var(--sn-border);border-radius:12px;background:var(--sn-card);overflow:hidden;margin-bottom:16px}.sncp-panel-heading{padding:23px 26px 19px;border-bottom:1px solid var(--sn-border)}.sncp-panel-heading h2{font-size:17px;font-weight:600;letter-spacing:-.015em}.sncp-panel-heading p{font-size:13px;color:var(--sn-muted);margin-top:4px}
.sncp-steps{list-style:none;margin:0;padding:0 26px}.sncp-steps>li{display:flex;align-items:flex-start;gap:16px;padding:23px 0;border-bottom:1px solid var(--sn-border)}.sncp-steps>li:last-child{border:0}.sncp-step-number{display:flex;align-items:center;justify-content:center;width:28px;height:28px;flex-shrink:0;border:1px solid var(--sn-border);border-radius:50%;font-size:12px;font-weight:600;background:var(--sn-soft)}.sncp-step-copy{flex:1;min-width:0}.sncp h3{font-weight:600;font-size:14px;margin:2px 0 5px}
.sncp-step-copy>p,.sncp-settings-body p{color:var(--sn-muted);font-size:13px;max-width:720px}.sncp-domain{display:inline-block;max-width:100%;margin-top:10px;background:var(--sn-soft);border:1px solid var(--sn-border);border-radius:5px;padding:4px 9px;font-size:12px;overflow-wrap:anywhere}.sncp-check-summary{font-size:12px!important;margin-top:9px!important}.sncp-needs-attention{color:#9a6219}.dark .sncp-needs-attention{color:#efd498}
.sncp-details{margin-top:13px}.sncp summary{cursor:pointer;list-style:none;font-size:12px;font-weight:600;color:var(--sn-accent);display:flex;align-items:center;gap:9px;min-height:28px}.sncp summary::-webkit-details-marker{display:none}.sncp summary:before{content:'›';font-size:19px;line-height:1;transition:transform .15s}.sncp details[open]>summary:before{transform:rotate(90deg)}
.sncp-details-body{border-radius:8px;background:var(--sn-soft);margin-top:12px;padding:17px 19px;font-size:12px;max-width:760px}.sncp-details-body p{color:var(--sn-muted);margin:13px 0 7px}.sncp-checks{list-style:none;margin:0;padding:0}.sncp-checks li{display:flex;justify-content:space-between;align-items:baseline;gap:15px;padding:7px 0;border-bottom:1px solid var(--sn-border)}.sncp-checks strong{font-size:11px;font-weight:600}.sncp pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px;background:var(--sn-card);border:1px solid var(--sn-border);border-radius:5px;padding:10px;margin:8px 0}.sncp-text-link{color:var(--sn-accent);text-decoration:underline;text-underline-offset:3px}

.sncp-readiness-form{margin-top:15px}.sncp-checkbox{display:flex;align-items:flex-start;gap:9px;font-size:13px;cursor:pointer;margin-bottom:15px}.sncp-checkbox input{appearance:auto;accent-color:#6d28d9;width:16px;height:16px;flex-shrink:0;margin-top:2px}
.sncp-settings>summary{color:var(--sn-muted);padding:17px 25px}.sncp-settings-body{border-top:1px solid var(--sn-border);padding:0 26px}.sncp-settings-body>div{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:21px 0}.sncp-settings-body>div+div{border-top:1px solid var(--sn-border)}.sncp-settings-body form{flex-shrink:0}.sncp-settings-body p{max-width:600px;font-size:12px}
.sncp-settings>.sncp-details-body{margin:0 25px 20px;max-width:none}.sncp-details-body>p:first-child{margin-top:0}.sncp-details-body>.sncp-text-link{display:inline-block;margin-top:12px}
.sncp-footer{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;color:var(--sn-muted);font-size:11px;padding:10px 2px}.sncp-footer>span{white-space:nowrap}.sncp-footer strong{font-weight:600}
.sncp-notice{padding:13px 17px;border:1px solid #06b6d455;background:#06b6d412;border-radius:9px;margin-bottom:18px;font-size:13px}.sncp-notice-error{border-color:#df787855;background:#df787812}
@media(max-width:1100px){.sncp-visual{display:none}}
@media(max-width:720px){.sncp-header{flex-direction:column;gap:15px}.sncp h1{font-size:26px}.sncp-hero{padding:25px 23px}.sncp-hero h2{font-size:26px}.sncp-status-grid{grid-template-columns:1fr;gap:10px}.sncp-panel-heading{padding:20px}.sncp-steps{padding:0 20px}.sncp-steps>li{gap:12px}.sncp-settings-body>div{align-items:flex-start;flex-direction:column;gap:14px}.sncp-footer{flex-direction:column;gap:7px}.sncp-checks li{flex-wrap:wrap;gap:4px}.sncp-details-body{padding:12px}.sncp-status{padding:16px}}

.sncp-logo{width:192px;height:auto;max-width:60%;display:block}.sncp-logo-dark{display:none}.dark .sncp-logo-light{display:none}.dark .sncp-logo-dark{display:block}
