.sncp{--sn-ink:#182a2c;--sn-muted:#626e72;--sn-border:#e3e8e7;--sn-card:#fff;--sn-soft:#f5f8f7;--sn-green:#167366;--sn-good:#176c4f;color:var(--sn-ink);max-width:1180px;margin:0 auto;padding:10px 4px 28px;font-size:14px;line-height:1.55}
.dark .sncp{--sn-ink:#e9efee;--sn-muted:#a3b3b2;--sn-border:#354744;--sn-card:#202c2a;--sn-soft:#283733;--sn-green:#7ad6b9;--sn-good:#8bdfba}
.sncp h1,.sncp h2,.sncp h3,.sncp p{margin:0}
.sncp-header{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:26px}
.sncp-eyebrow{font-size:10px;font-weight:700;letter-spacing:.16em;color:var(--sn-muted);margin-bottom:7px!important}
.sncp h1{display:flex;align-items:center;gap:14px;font-size:29px;line-height:1.2;font-weight:650;letter-spacing:-.035em}
.sncp-preview{font-size:10px;letter-spacing:0;font-weight:500;line-height:1.3;border:1px solid var(--sn-border);border-radius:5px;padding:4px 7px;color:var(--sn-muted)}
.sncp-lead{margin-top:10px!important;max-width:620px;color:var(--sn-muted)}
.sncp-button{display:inline-flex;align-items:center;justify-content:center;gap:14px;min-height:39px;padding:9px 15px;border-radius:8px;border:1px solid transparent;line-height:1.3;font-size:13px;font-weight:600;cursor:pointer;text-decoration:none;white-space:normal;transition:background .15s,box-shadow .15s}
.sncp-button:focus-visible,.sncp summary:focus-visible,.sncp a:focus-visible,.sncp input:focus-visible{outline:3px solid #59c8ad;outline-offset:3px}
.sncp-button-primary{background:#d8f6a9;color:#182e24;box-shadow:0 1px 2px #061e1a33}.sncp-button-primary:hover{background:#e6ffbd}
.sncp-button-secondary{border-color:var(--sn-border);background:var(--sn-card);color:var(--sn-ink);box-shadow:0 1px 2px #172e2510}.sncp-button-secondary:hover{background:var(--sn-soft)}
.sncp-button-danger{background:transparent;border-color:var(--sn-border);color:#b93c37}.dark .sncp-button-danger{color:#ffa7a1}.sncp-button-danger:hover{background:#fa777712}
.sncp-hero{display:flex;align-items:center;justify-content:space-between;gap:24px;overflow:hidden;border-radius:15px;background:linear-gradient(118deg,#193d38,#214e42);color:#f5fff9;padding:30px 34px;margin-bottom:20px}
.sncp-hero-copy{max-width:660px}.sncp-connection{display:inline-flex;flex-wrap:wrap;align-items:center;gap:8px;color:#c5ded3;font-size:12px;overflow-wrap:anywhere}
.sncp-dot{width:7px;height:7px;background:#d1c396;border-radius:50%}.sncp-dot.is-connected{background:#b7ef97;box-shadow:0 0 0 4px #b7ef9714}
.sncp-hero h2{font-size:30px;line-height:1.22;letter-spacing:-.045em;font-weight:600;margin:14px 0 10px}.sncp-hero p{color:#c6ded4;max-width:520px}
.sncp-actions{display:flex;align-items:center;flex-wrap:wrap;gap:20px;margin-top:23px}.sncp-hero-link{color:#e2eee8;font-size:13px;text-decoration:underline;text-underline-offset:4px}
.sncp-visual{display:flex;align-items:center;flex-shrink:0;padding:15px 2px 25px 12px;transform:rotate(-5deg)}
.sncp-visual-node{position:relative;display:flex;justify-content:center;align-items:center;width:62px;height:68px;border:1px solid #ffffff35;border-radius:13px;background:#ffffff10;font-size:31px;font-weight:600;color:#defac3;box-shadow:0 12px 22px #09241c22}
.sncp-visual-node>span{position:absolute;top:78px;left:-5px;right:-5px;text-align:center;color:#bbd5c9;font-size:10px;letter-spacing:.02em;font-weight:400}
.sncp-visual-statamic{transform:rotate(10deg);color:#fff}.sncp-visual-line{display:flex;align-items:center;justify-content:center;width:40px;color:#bbd799;font-size:17px}

.sncp-status-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px}.sncp-status{display:flex;align-items:flex-start;gap:12px;background:var(--sn-card);border:1px solid var(--sn-border);border-radius:11px;padding:19px 20px}.sncp-status h2{font-size:13px;font-weight:650;display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-bottom:5px}.sncp-status p{font-size:12px;color:var(--sn-muted)}
.sncp-status-icon{display:flex;align-items:center;justify-content:center;flex-shrink:0;width:30px;height:30px;border-radius:9px;background:var(--sn-soft);color:var(--sn-muted);font-size:14px}.sncp-pill{font-size:10px;font-weight:500;color:var(--sn-muted);background:var(--sn-soft);padding:2px 7px;border-radius:5px}.sncp .is-good{color:var(--sn-good)}.sncp-status-icon.is-good{background:#45956b14}
.sncp-panel{border:1px solid var(--sn-border);border-radius:12px;background:var(--sn-card);overflow:hidden;margin-bottom:16px}.sncp-panel-heading{padding:23px 26px 19px;border-bottom:1px solid var(--sn-border)}.sncp-panel-heading h2{font-size:17px;font-weight:600;letter-spacing:-.015em}.sncp-panel-heading p{font-size:13px;color:var(--sn-muted);margin-top:4px}
.sncp-steps{list-style:none;margin:0;padding:0 26px}.sncp-steps>li{display:flex;align-items:flex-start;gap:16px;padding:23px 0;border-bottom:1px solid var(--sn-border)}.sncp-steps>li:last-child{border:0}.sncp-step-number{display:flex;align-items:center;justify-content:center;width:28px;height:28px;flex-shrink:0;border:1px solid var(--sn-border);border-radius:50%;font-size:12px;font-weight:600;background:var(--sn-soft)}.sncp-step-copy{flex:1;min-width:0}.sncp h3{font-weight:600;font-size:14px;margin:2px 0 5px}
.sncp-step-copy>p,.sncp-settings-body p{color:var(--sn-muted);font-size:13px;max-width:720px}.sncp-domain{display:inline-block;max-width:100%;margin-top:10px;background:var(--sn-soft);border:1px solid var(--sn-border);border-radius:5px;padding:4px 9px;font-size:12px;overflow-wrap:anywhere}.sncp-check-summary{font-size:12px!important;margin-top:9px!important}.sncp-needs-attention{color:#9a6219}.dark .sncp-needs-attention{color:#efd498}
.sncp-details{margin-top:13px}.sncp summary{cursor:pointer;list-style:none;font-size:12px;font-weight:600;color:var(--sn-green);display:flex;align-items:center;gap:9px;min-height:28px}.sncp summary::-webkit-details-marker{display:none}.sncp summary:before{content:'›';font-size:19px;line-height:1;transition:transform .15s}.sncp details[open]>summary:before{transform:rotate(90deg)}
.sncp-details-body{border-radius:8px;background:var(--sn-soft);margin-top:12px;padding:17px 19px;font-size:12px;max-width:760px}.sncp-details-body p{color:var(--sn-muted);margin:13px 0 7px}.sncp-checks{list-style:none;margin:0;padding:0}.sncp-checks li{display:flex;justify-content:space-between;align-items:baseline;gap:15px;padding:7px 0;border-bottom:1px solid var(--sn-border)}.sncp-checks strong{font-size:11px;font-weight:600}.sncp pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px;background:var(--sn-card);border:1px solid var(--sn-border);border-radius:5px;padding:10px;margin:8px 0}.sncp-text-link{color:var(--sn-green);text-decoration:underline;text-underline-offset:3px}

.sncp-readiness-form{margin-top:15px}.sncp-checkbox{display:flex;align-items:flex-start;gap:9px;font-size:13px;cursor:pointer;margin-bottom:15px}.sncp-checkbox input{appearance:auto;accent-color:#20735c;width:16px;height:16px;flex-shrink:0;margin-top:2px}
.sncp-settings>summary{color:var(--sn-muted);padding:17px 25px}.sncp-settings-body{border-top:1px solid var(--sn-border);padding:0 26px}.sncp-settings-body>div{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:21px 0}.sncp-settings-body>div+div{border-top:1px solid var(--sn-border)}.sncp-settings-body form{flex-shrink:0}.sncp-settings-body p{max-width:600px;font-size:12px}
.sncp-footer{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;color:var(--sn-muted);font-size:11px;padding:10px 2px}.sncp-footer>span{white-space:nowrap}.sncp-footer strong{font-weight:600}
.sncp-notice{padding:13px 17px;border:1px solid #53b28d55;background:#53b28d12;border-radius:9px;margin-bottom:18px;font-size:13px}.sncp-notice-error{border-color:#df787855;background:#df787812}
@media(max-width:1100px){.sncp-visual{display:none}}
@media(max-width:720px){.sncp-header{flex-direction:column;gap:15px}.sncp h1{font-size:26px}.sncp-hero{padding:25px 23px}.sncp-hero h2{font-size:26px}.sncp-status-grid{grid-template-columns:1fr;gap:10px}.sncp-panel-heading{padding:20px}.sncp-steps{padding:0 20px}.sncp-steps>li{gap:12px}.sncp-settings-body>div{align-items:flex-start;flex-direction:column;gap:14px}.sncp-footer{flex-direction:column;gap:7px}.sncp-checks li{flex-wrap:wrap;gap:4px}.sncp-details-body{padding:12px}.sncp-status{padding:16px}}
